### ISSUE TITLE
Support "Read by everyone" in sample app

### ISSUE THREAD

**Issue by Hirobreak** [Criptext/Monkey-Chat-Web#138]
feedback to show that all users have read a message

**Comment by GianniCarlo** [comment]
cc @fluxny75 we need a design for this

**Comment by fluxny75** [comment]
@GianniCarlo before i can provide a design I need:
1) Context, is this for group chat?
2) Sample App, need to see the sample app that Daniel will show to me on Friday 7-19-16
3) Are there any limitation?

**Comment by GianniCarlo** [comment]
@fluxny75 
1) yup, group chat
2) This particular issue is for web chat, we will integrate it later for mobile
3) There's no way to know the exact time when a message was read, only that it was read by x person

**Comment by fluxny75** [comment]
@GianniCarlo -> there needs to be a design session at this point I only see one option to show if a message was read and by whom.
- Clik on the message and show a modal popup with the metadata. Thoughts?

**Comment by fluxny75** [comment]
@erikaperugachi @Hirobreak @GianniCarlo -- please look at the visual attached to this ticket - this is how the message info for a group should look. if you happen to have any questions please let me know.

![webchat_messageinfo](https://cloud.githubusercontent.com/assets/2845905/18070567/6560ba4c-6e14-11e6-8e49-859b79a41525.png)

**Comment by erikaperugachi** [comment]
Este issue no debería estar aqui, lo cierro y lo dirijo a react-monkey-ui
