### ISSUE TITLE
Show METADATA of user and groups UX/UI

### ISSUE THREAD

**Issue by luisloaiza** [Criptext/Monkey-Chat-Web#146]
Example of SLACK

<img width="738" alt="captura de pantalla 2016-07-29 a las 13 22 04" src="https://cloud.githubusercontent.com/assets/189032/17259191/ffccea62-558f-11e6-9e01-75cf7f465402.png">

AS we see in the right sidebar we have all the info related to the GROUP.

WE should have a way to add a side bar or the BURGER ICON in the right , to see this info. I already speak with @Hirobreak to show this info, but I think this is a good way to show in UI @fluxny75 .

**Comment by luisloaiza** [comment]
Info I suggest to show.
- Members
- WHo is online
- ADmins
- Requests to join the group if private
- SET private or public
- Options in members to remove if I am admin
- Custom metadata showing

All this must be built in the UI KIT and sample

**Comment by fluxny75** [comment]
@luisloaiza a few suggestion of information that should have:
- Who read the message
- Members phone number
- Ability to call a member
  What is the time line and when this is planned to be implemented?

cc @Hirobreak

**Comment by erikaperugachi** [comment]
- Photo
- Name conversation
- # members online (to group chat) / online status (to personal chat)
- list members (to chat group)
  - who is admin
  - who is online
- show custome info data (with title and description) (to chat group)
- remove member only if you are admin (to chat group)

cc: @fluxny75
